In [22]:
# Bibliotecas
import sqlite3
import pandas as pd

In [23]:
def rodar_consulta(query):
    """ Executa uma query SQL e retorna o resultado formatado como DataFrame. """

    conn = sqlite3.connect("loja.db")
    
    df = pd.read_sql_query(query, conn)
    
    return df

Formatação de query: https://sqlformat.org/

SQLite online: https://sqliteonline.com/

<br>
<br>

### SELECT

In [24]:
# Trazer tudo de produtos

query = f"""
    SELECT *
    FROM produtos;
"""

print(query)

data = rodar_consulta(query)
data

    SELECT *
    FROM produtos;

   id              nome  preco
0   1  Teclado Mecânico  250.0
1   2     Mouse Sem Fio  120.0
2   3     Monitor 24pol  890.0
3   4     Headset Gamer  310.0

In [26]:
# Trazer apenas nome e preço

query = f"""
    SELECT nome
    FROM produtos;
"""

data = rodar_consulta(query)
data

               nome
0  Teclado Mecânico
1     Mouse Sem Fio
2     Monitor 24pol
3     Headset Gamer

<br>
<br>

### WHERE (Filtrar linhas)

In [28]:
# Produtos com valor acima de 200 reais

query = f"""
    SELECT
        nome,
        preco
    FROM produtos
    WHERE preco > 305;
"""

data = rodar_consulta(query)
data

            nome  preco
0  Monitor 24pol  890.0
1  Headset Gamer  310.0

In [33]:
# Clientes de uma cidade específica

query = f"""
    select *
    from clientes
    WHERE cidade = 'Curitiba';
"""

data = rodar_consulta(query)
data

   id        nome    cidade
0   3  Carla Dias  Curitiba

<br>
<br>

### ORDER BY e LIMIT (Ordenar e limitar)

Muito útil para rankings ou pegar amostras rápidas para análise

DESC - Indica a ordenação decrescente
ASC - Indica a ordenação crescente (basta omitir, uma vez que é o standard)

In [39]:
# Produtos do mais caro para o mais barato, mostrando só o top 2

query = f"""
    SELECT
        NOME,
        preco
    FROM produtos
    ORDER BY preco DESC  -- "order by" ordena o output
    LIMIT 3;
"""

data = rodar_consulta(query)
data

               nome  preco
0     Monitor 24pol  890.0
1     Headset Gamer  310.0
2  Teclado Mecânico  250.0

<br>
<br>

### JOIN (Cruzar tabelas)

Juntar os pedidos com os nomes reais de quem comprou e o que comprou, em vez de ver apenas números de ID soltos:

In [ ]:
query = f"""
    SELECT 
        clientes.nome AS cliente,
        produtos.nome AS produto,
        pedidos.quantidade,
        (produtos.preco * pedidos.quantidade) AS total
    FROM pedidos
    JOIN clientes ON pedidos.cliente_id = clientes.id
    JOIN produtos ON pedidos.produto_id = produtos.id;
"""

data = rodar_consulta(query)
data

https://www.instagram.com/p/DZjGfvumMtD/

https://www.linkedin.com/posts/ajayyadav1996_sql-joins-cheatsheet-activity-7445793807624941568-9-bl

**Resumo dos Tipos de JOIN**

• INNER JOIN: Retorna apenas os registros que possuem correspondência em ambas as tabelas. (É o padrão).   
• LEFT JOIN (ou LEFT OUTER JOIN): Retorna todos os registros da tabela da esquerda, e os registros correspondentes da tabela da direita (se não houver correspondência, retorna NULL).  
• RIGHT JOIN (ou RIGHT OUTER JOIN): Retorna todos os registros da tabela da direita, e os correspondentes da esquerda (se não houver correspondência, retorna NULL).  
• FULL JOIN (ou FULL OUTER JOIN): Retorna todos os registros de ambas as tabelas quando houver uma correspondência em uma delas.